# Perfil activo por defecto (dev para desarrollo local, prod para produccion)
spring.profiles.active=dev

# Configuracion de Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method

# JWT Configuration - Using a 256-bit secure key
app.jwt-secret=mySecretKeyForJWTTokenGenerationThatIsLongEnoughToMeetThe256BitRequirementForHMACSHA256Algorithm
app.jwt-expiration-ms=86400000



# Habilitar referencias circulares
spring.main.allow-circular-references=true