# Configuracion de desarrollo (SQLite)
spring.datasource.url=jdbc:sqlite:src/main/resources/database/alquileres.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Configuracion de JPA/Hibernate para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion del servidor
server.port=8081

# Configuracion de logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

